const picturesData = [
  {
    img: "image1",
    title: "education",
    src: "education.jpg",
    subtitle: "Because we are all students",
    icon: "AcademicCapIcon",
  },
  {
    img: "image2",
    title: "recreational",
    src: "recreation.jpg",
    subtitle: "Who doesn't like having fun?",
    icon: "SunIcon",
  },
  {
    img: "image3",
    title: "social",
    src: "social.jpg",
    subtitle: "Need some friends?",
    icon: "UserGroupIcon",
  },
  {
    img: "image4",
    title: "diy",
    src: "diy.jpg",
    subtitle: "Do It Yourself!",
    icon: "BeakerIcon",
  },
  {
    img: "image5",
    title: "charity",
    src: "charity.jpg",
    subtitle: "There's always more to give",
    icon: "GiftIcon",
  },
  {
    img: "image6",
    title: "cooking",
    src: "cooking.jpg",
    subtitle: "Spend less time on Seamless and more in your kitchen",
    icon: "CakeIcon",
  },
  {
    img: "image7",
    title: "relaxation",
    src: "relaxation.jpg",
    subtitle: "Stressed? Just chill out",
    icon: "MoonIcon",
  },
  {
    img: "image8",
    title: "music",
    src: "music.jpg",
    subtitle: "Get them vibes",
    icon: "MusicNoteIcon",
  },
  {
    img: "image9",
    title: "busy work",
    src: "busywork.jpg",
    subtitle: "Get up off that coach NOW",
    icon: "DesktopComputerIcon",
  },
  {
    img: "image10",
    title: "random",
    src: "random.jpg",
    subtitle: "Get a random activity",
    icon: "ColorSwatchIcon",
  },
];
export default picturesData;
